name: Security Scan

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit detect-secrets
          pip install -r requirements.txt      - name: Run Bandit security scan
        run: |
          bandit -r . --severity-level medium --confidence-level medium \
          -x "./venv-genai/*,./venv-learnpy/*,./tests/*,./chroma_langchain_db/*,./chroma_ollama_db/*,./dbt-env/*" \
          -f txt \
          --exit-zero

      - name: Scan for secrets
        run: |
          detect-secrets scan \
          --exclude-lines 'GOOGLE_API_KEY|API_KEY|SECRET_KEY' \
          --exclude-files 'venv-genai/.*|venv-learnpy/.*|tests/.*|.*\.pyc|.*\.git/.*|chroma_langchain_db/.*|chroma_ollama_db/.*|dbt-env/.*' \
          --exclude-secrets 'BEGIN CERTIFICATE' \
          .
